version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              apt-get update
              apt-get -y install wget zip unzip
      - run:
          name: Download Godot 3.1.1
          command: |
              wget -q https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_linux_headless.64.zip
              unzip Godot_v3.1.1-stable_linux_headless.64.zip
              mv Godot_v3.1.1-stable_linux_headless.64 godot
              chmod +x godot
      - run:
            name: Run Tests
            command: |
                ./godot -d -s --path $PWD addons/gut/gut_cmdln.gd
